### PR TITLE
fix: release correct amount of underlying in loans.redeem

### LINKED ISSUE #929: Loans: redeem not releasing correct amount due to rounding
In both `redeem`, the underlying amount is first converted to the lend token amount, after which the to-be released collateral is calculated by converting the lend token back to the underlying amount. This can have the consequence that the released collateral is less than what was requested in the `redeem` call. We should refactor to avoid the second conversion

### PR DESCRIPTION
**Pull request by sander2**
This fixes an issue where I called `loans.redeem` with `1e8` as amount, but only `1e8 - 1` actually got released. This was due to the amount first being converted to the lend_token_id and then back to the underlying. The change is that we now only do one conversion: in `loans.redeem` we do only a single `to_lend_id`, while in `loans.redeem_all` we do only a single `to_underlying_id`.  

Closes #929

### CODE REVIEW

File: crates/loans/src/lib.rs [hunk 1]
```diff
@@ -1033,42 +1029,14 @@ pub mod pallet {
...
-            // TODO: investigate whether it is possible to implement the conversion functions
-            // with guarantees that this always holds:
-            // `calc_underlying_amount(calc_collateral_amount(x)) = calc_collateral_amount(calc_underlying_amount(x))`
-            // Use the `converting_to_and_from_collateral_should_not_change_results` unit test to achieve this.
-            // If there are leftover lend_tokens after a `redeem_all` (because of rounding down), it would make it
-            // impossible to enforce "collateral toggle" state transitions.
-            Self::ensure_active_market(asset_id)?;
+            let free = Self::free_lend_tokens(asset_id, &who)?;
+            let reserved = Self::reserved_lend_tokens(asset_id, &who)?;
+            let used_collateral = Amount::max(&free, &reserved)?;
```
Comment (daniel-savu) [inline crates/loans/src/lib.rs:1034]: An account can't have both `free` and `reserved` lend tokens so this is correct but is not very easy to understand at first glance. Would be good to add a comment.

Comment (daniel-savu) [reply crates/loans/src/lib.rs:1034]: @sander2 Actually the caller could have both `free` and `reserved` lend tokens if they just mint and then lock some of their balance as vault collateral. If they lock more vault collateral than the free collateral, this call will end up failing although it should just redeem the free tokens.

Comment (sander2) [reply crates/loans/src/lib.rs:1034]: > @sander2 Actually the caller could have both `free` and `reserved` lend tokens if they just mint and then lock some of their balance as vault collateral. If they lock more vault collateral than the free collateral, this call will end up failing although it should just redeem the free tokens.

Oh shit I was assuming that free and reserved would be mutually exclusive.. That's not hard to fix but that means I reviewed some of the code with incorrect assumptions :(

File: crates/loans/src/lib.rs [hunk 2]
```diff
@@ -1007,68 +1012,31 @@ pub mod pallet {
...
-            // but that would cause the `accrue_interest_works_after_redeem_all` unit test to fail with
-            // left: `1000000000003607`,
-            // right: `1000000000003608`'
-
-            // Chaining `calc_underlying_amount` and `calc_collateral_amount` continuously decreases
-            // an amount because of rounding down, and having the current function call `do_redeem`
-            // would perform three conversions: lend_token -> token -> lend_token -> token.
-            // Calling `do_redeem_voucher` directly only performs one conversion: lend_token -> token,
-            // avoiding this edge case.
-            // TODO: investigate whether it is possible to implement the conversion functions
```
Comment (daniel-savu) [inline crates/loans/src/lib.rs:1046]: I would leave this TODO somewhere in the code

File: crates/currency/src/amount.rs [hunk 3]
```diff
@@ -224,6 +224,11 @@ mod math {
             Ok(if self.le(other)? { self.clone() } else { other.clone() })
         }
 
+        pub fn max(&self, other: &Self) -> Result<Self, DispatchError> {
```
Comment (daniel-savu) [inline crates/currency/src/amount.rs:227]: This function can be removed now

Comment (sander2) [reply crates/currency/src/amount.rs:227]: I chose to leave it since it's a potentially useful utility function

**Review by daniel-savu — APPROVED** [review]

File: crates/loans/src/lib.rs (hunk 2 above)
Comment (sander2) [reply crates/loans/src/lib.rs:1046]: Created https://github.com/interlay/interbtc/issues/934
